### PR TITLE
watermark: use standard list of variables

### PR DESCRIPTION
**Pull request by phweyland**
corresponds to PR #11238.

Sorry I'd missed this part.

### CODE REVIEW

**Comment by elstoc** [comment]
I didn't check myself but I assume you've confirmed that all of these variables are listed within the linked page?

**Comment by phweyland** [comment]
Fixing this currently. I've been a bit harsh here ... :)

**Comment by phweyland** [comment]
Should be more accurate now.

**Comment by elstoc** [comment]
Thanks!

**Pull request merged**
