### PR TITLE
Add high-contrast themes to general preferences

### PR DESCRIPTION
**Pull request by ralfbrown**

### CODE REVIEW

**Comment by elstoc** [comment]
Would you mind looking up the appropriate darktable PR reference and providing a link to it when you raise dtdocs PRs please. Just helps with the admin.

**Comment by ralfbrown** [comment]
PR 17245.

**Comment by elstoc** [comment]
Thanks. If you could post them as links (https://github.com/darktable-org/darktable/pull/17245) that would allow me to be really really lazy :)

**Comment by elstoc** [comment]
LGTM thanks

**Comment by elstoc** [comment]
@ralfbrown: One more thing to note here. I know you have the power to amend labels in darktable PRs but I'd prefer to do that myself when I'm satisfied the documentation is complete. Also generally I only remove the "documentation" labels entirely if I don't think a PR needs documentation updates. For completed documentation I remove the "documentation-pending" label and replace it with a "documentation-complete" label.

**Pull request merged**
