### PR TITLE
update variables page with new substitutable EXIF and GPS variables

### PR DESCRIPTION
**Pull request by ralfbrown**

### CODE REVIEW

**Comment by elstoc** [comment]
Thanks @ralfbrown. Please can you remove the submodule update from this branch, and then I'm happy to merge.

**Comment by elstoc** [comment]
Actually no, this will have to wait until we've finalised the 4.8 updates so no hurry.

**Comment by ralfbrown** [comment]
I don't know how that happened, and when I tried pushing again after a submodule update, git told me everything is up-to-date and refushed to push....

**Comment by elstoc** [comment]
Yeah if you look at the commit, it thinks everything is the same, it's just a different commit hash. Maybe squash and rebase? If you can't fix it I'm happy to just rekey this stuff into a new branch when we start merging changes for 5.0

**Comment by ralfbrown** [comment]
I had already tried rebase followed by submodule update, but that indeed did not change the commit hashes.  Squashing was successful.

**Comment by elstoc** [comment]
Hmm it still seems to think the submodule is updated. Shrug

**Comment by ralfbrown** [comment]
One more variable to add:
```
$(IMAGE.TAGS.HIERARCHY)    tags list, preserving hierarchy
```
Your call  on whether to rename TAGS to the now-preferred IMAGE.TAGS  or make a duplicate entry, since  both are still in the autocomplete list.

**Comment by ralfbrown** [comment]
Superceded by 683.

**Pull request closed without merging**
