### PR TITLE
color-calibration: add diagrams to better illustrate channel mixing

### PR DESCRIPTION
**Pull request by matt-maguire**
Add some diagrams to show color mixing as sliders/crosstalk, and also as rotations of basis vectors in 3D colorspace.

### CODE REVIEW

**Comment by elstoc** [comment]
@aurelienpierre I'd like your opinion on this please.

**Comment by aurelienpierre** [comment]
Only electrical engineers will be able to read those graphs.

**Comment by johnny-bit** [comment]
I asked my wife for her input! It seems that english major can also understand diagrams ;) "the sliders are bit hard to see and without them the whole thing makes no sense" :)

**Comment by aurelienpierre** [comment]
I'm not opposed to that, just concerned that it might raise more confusion.

**Pull request closed without merging**
