### PR TITLE
Add weasyprint and render a PDF from the site sources.

### LINKED ISSUE #144: Auto-build pdf with github-actions
I'm not sure if the current method of building the pdf will work well with gh-actions.

### PR DESCRIPTION
**Pull request by paperdigits**
Auto generates a PDF of the docs. Fixes #144.

### CODE REVIEW

**Comment by paperdigits** [comment]
@johnny-bit is it OK to bump the container to Ubuntu 20.04?

**Comment by johnny-bit** [comment]
Yes. No problem in that.

**Comment by elstoc** [comment]
Looks good. Just need to add a link to the pdf from the front page then I assume.

**Comment by paperdigits** [comment]
Yes, a link will do. Do we want that in the content or as part of the theme?

**Comment by elstoc** [comment]
If it's in a consistent location on the website put it into the root index.html

**Comment by TurboGit** [comment]
Really nice ! Thanks for the hard work on the documentation.

**Pull request merged**
