### PR TITLE
Fix typo: Lighroom

### PR DESCRIPTION
**Pull request by lekum**

### CODE REVIEW

**Comment by paperdigits** [comment]
Hi! Good catch on the typo, but we never ever edit PO files directly for dtdocs, they must be changed via weblate.

The change to the English markdown file can stay though. 

Please amend your PR.

**Comment by lekum** [comment]
PR amended, thanks @paperdigits for your comment.

**Comment by paperdigits** [comment]
Sorry to be such a picky turd, but the PO files can't change at all. If you can squash the two commits together, it should be fine. But any change to the PO files will screw up out translation app.

**Comment by lekum** [comment]
No problem, I'll squash the two commits into one and force push. I supposed this decision could be done at merge (squash) time but no problem from my side.

**Pull request merged**
