### PR TITLE
First bunch of opencl 46 suggestions

### PR DESCRIPTION
**Pull request by jenshannoschwalm**
- preferences
- setting up

@elstoc had messed up my authentication stuff ...

### CODE REVIEW

**Comment by jenshannoschwalm** [comment]
BTW - have just seen that you included lens vignetting and the backthumbs crawler stuff already. Do you have any questions about that or other things i left undocumented?

**Comment by elstoc** [comment]
If you could look over the stuff I've done and let me know if it needs anything more that'd be great. If there's anything more that's undocumented it's because I haven't started looking at it yet, so I don't yet know if I have questions.

**Comment by jenshannoschwalm** [comment]
No, I checked my to-do list for updated dtdocs and there is only opencl stuff left out.

**Comment by elstoc** [comment]
Nice, thanks. I'll take a look at it this weekend

**Comment by elstoc** [comment]
LGTM thanks!

**Pull request merged**
