### PR TITLE
chromatic aberration documentation

### PR DESCRIPTION
**Pull request by rawfiner**
Documentation for chromatic aberration module.
Please tell me if anything should be extended or if something is unclear :-)

### CODE REVIEW

**Comment by rawfiner** [comment]
also, git submodule update failed, it asks for a gitlab username, so I didn't try to build. I hope there is no formatting mistake in the markdown...

**Comment by elstoc** [comment]
> also, git submodule update failed, it asks for a gitlab username

Odd. We moved the submodules off gitlab ages ago. Perhaps you need to init again?

**Comment by rawfiner** [comment]
> Perhaps you need to init again?

That works! Sorry for the noise...

**Comment by elstoc** [comment]
Anyway this looks fine. I'll merge and copy-edit (will probably move the workflow section to the top) and I'll let you know if I need anything more. Thanks!

**Comment by paperdigits** [comment]
The .gitmodules file is tracked by git... Are you up to date with master?

**Comment by rawfiner** [comment]
Great thank you!
Yes I was up to date, but I needed to deinit the submodule to init them again as the url changed since last time I used the project

**Comment by elstoc** [comment]
@rawfiner: I've pushed my copy-edit if you wanted to take a look at it.

**Comment by rawfiner** [comment]
Thank you, I took a look at it and it is perfect!

**Pull request merged**
