### PR TITLE
Change in the content.pot file.

### PR DESCRIPTION
**Pull request by lebmich**
New wording to clarify the concept of duplicate instance. I hope ...

### CODE REVIEW

**Comment by elstoc** [comment]
Hmm I'm not convinced this is really any clearer. Also, you can't just modify the content.pot file, you have to change the original markdown files themselves.

**Comment by lebmich** [comment]
In the English version of the user manual we have:

duplicate instance
    Create a new instance of the current module with all of its parameters **inherited from the parent module**.

I think the expression "inherited from the parent module" is not precise enough. What must be expressed is that the values of the parameters of the new instance are those of the parameters of the instance which is being duplicated.

**Comment by paperdigits** [comment]
That is what the phrase "inherited from the parent" means though.

**Comment by lebmich** [comment]
Maybe we could write "inherited from the parent **instance**"

**Comment by lebmich** [comment]
or better : "inherited from **its** parent instance"

**Comment by lebmich** [comment]
We could write:
duplicate instance
Create a new instance of the current module with its parameters settings inherited from its parent instance.

**Comment by elstoc** [comment]
The rest of the section refers to "current instance" so we'll go with that

**Pull request closed without merging**
