### PR TITLE
Translation

### PR DESCRIPTION
**Pull request by paperdigits**
Get some scripts and a workflow together for converting all the markdown files to PO.

The current scripts, `tools/generate-translations.sh` creates a temporary po4a config file and then runs po4a.

This addresses #84

### CODE REVIEW

**Comment by paperdigits** [comment]
The current script almost works, but a few options for po4a that are listed in the man page are flagged by po4a as being not working. Also need to figure out how to parse the yaml fields in the post headers correctly.

**Comment by elstoc** [comment]
Is this likely to work on the gh-pages site or will we need to tweak it (e.g. the current gh-pages doesn't include `/en` in its url)?

**Comment by paperdigits** [comment]
It should work on gh-pages.

**Comment by elstoc** [comment]
@paperdigits please can you also include some documentation of the translation process either in the readme or in contributing.md.

**Comment by paperdigits** [comment]
I think this is ready for prime time. Please test the instructions I've written.

**Comment by elstoc** [comment]
Could we have a link to the translation section from the front page and/or the contributing page please

**Comment by jpellegrini** [comment]
In `translating.md`, there should be a `cd ..` between steps 4 and 5 in section "Generating a PO file". No big deal anyway...

**Comment by jpellegrini** [comment]
I tested this translating workflow for `.po` files, and it worked perfectly!
Thanks to all developers who took the time to make it possible to work with `.po` files.
I'll start translating as soon as this PR is merged.

**Comment by elstoc** [comment]
> Thanks to all developers who took the time to make it possible to work with .po files.

All the credit goes to @paperdigits

**Comment by elstoc** [comment]
How do the weblate translations find their way back into the repository?

**Comment by jpellegrini** [comment]
> How do the weblate translations find their way back into the repository?

Good point. And another question: if any of the translated languages have a translation team, is it OK to have part of the work done via weblate and part directly through .po file editing?  (Not planning to do it; just thought it would be good to tell people if it's possible or not)

**Comment by paperdigits** [comment]
When the translation in weblate hits 100%, weblate will issue a PR against our repo. I don't think it is possible to work in weblate and out side of weblate at the same time. But I'm not a weblate expert, so I might be wrong.

**Comment by elstoc** [comment]
Reading the docs it looks like you can export and import from weblate, so the best thing might be to do everything via weblate, and those that don't want to use the web interface can export/import PO files from there. Otherwise we're going to have fun trying to keep stuff aligned.

**Comment by jpellegrini** [comment]
> Reading the docs it looks like you can export and import from weblate, so the best thing might be to do everything via weblate, and those that don't want to use the web interface can export/import PO files from there. Otherwise we're going to have fun trying to keep stuff aligned.

Ok - but if committing partial translations is not a good thing, then maybe it would be nice to add that to the instructions.

**Comment by elstoc** [comment]
I think that was more about deciding when the translations from weblate get incorporated into the dtdocs repository, and presumably that sort of stuff is going to be configurable. All this will take some trial-and-error to get right.

**Comment by paperdigits** [comment]
I think I was wrong. It seems like if we use weblate, then weblate will manage the translations 100%. You can download the PO files from weblate, then upload them when you're done. Weblate has a cli tool as well, if that is what you like.

**Comment by paperdigits** [comment]
For an easy first project, I added the yaml strings of the hugo PDF theme we use to generate the PDF: https://weblate.pixls.us/projects/darktable/hugo-darktable-docs-pdf-theme/

If someone wants to try and translate those 8 or so strings, please do.

**Comment by paperdigits** [comment]
Closes #84

**Pull request merged**
