### PR TITLE
Currently, the default theme is darktable-elegant-grey

### PR DESCRIPTION
**Pull request by victoryforce**
After accepting https://github.com/darktable-org/darktable/pull/11936 the default theme is `darktable-elegant-grey`.

### CODE REVIEW

**Comment by elstoc** [comment]
On second thoughts this change is not correct. While the default theme _is_ `darktable-elegant-grey`, the bulk of the css remains in `darktable.css`, so this needs some rewording as well.

**Comment by victoryforce** [comment]
I see. Indeed. What would be your suggestion for change? I think we could just remove the phrase about where most of the css code is located.

**Comment by elstoc** [comment]
Since this section is more about how the themes are constructed, I might be tempted to go the other way - i.e. remove the bit about the default theme and change it to say that darktable.css is where most of the css code is located.

**Comment by victoryforce** [comment]
You are right. Done.

**Comment by elstoc** [comment]
LGTM

**Pull request merged**
